### ISSUE TITLE
Error: unknown flag: --wait

### ISSUE THREAD

**Issue by kamorana** [magento/magento2-kubernetes-devbox#117]
I try to make a clean setup of the devbox, but I have some issues regarding my kubernetes, helm, docker versions. I did a fresh clone and after setting up the basic configurations, init-project.sh throws an error. Is there an overview on which version of which program we can use with this box or what do I have to do to make it run again (it ran, before I made a reinstall of macos on a new macbook). I am currently running on MacOs Mojave 10.14.6.

💿  Downloading VM boot image ...
    > minikube-v1.5.1.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.5.1.iso: 143.76 MiB / 143.76 MiB [-] 100.00% 40.76 MiB p/s 4s
🔥  Creating hyperkit VM (CPUs=2, Memory=4096MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.15.6 on Docker '18.09.9' ...
💾  Downloading kubelet v1.15.6
💾  Downloading kubeadm v1.15.6
🚜  Pulling images ...
🚀  Launching Kubernetes ...
⌛  Waiting for: apiserver
🏄  Done! kubectl is now configured to use "minikube"
✅  ingress was successfully enabled
✅  heapster was successfully enabled

... 

[2019-12-18 16:21:51] Configuring kubernetes cluster on the minikube [init_project.sh]
Error: unknown flag: --wait

**Comment by AlexObreja** [comment]
Hi @kamorana , take a look at my solution on issue #116 
That solution worked for me.

**Comment by kamorana** [comment]
Amazing! it finally works again!
