### ISSUE TITLE
composer.sh not found

### ISSUE THREAD

**Issue by kamorana** [magento/magento2-kubernetes-devbox#22]
**Problems at install step 3**
By calling:
helm init-magento`
`
**I am getting the following error:**
"..." magento2-devbox/scripts/host/composer.sh: No such file or directory [Unknown source file]

The script is correct, because the file does not exist.

**Comment by valdislav** [comment]
Note: when checkout_source_from composer.

**Comment by valdislav** [comment]
@kamorana Thank you for a report.
