### ISSUE TITLE
https://k8s.gcr.io/v2/ Repo Issues

### ISSUE THREAD

**Issue by JackWormUK** [magento/magento2-kubernetes-devbox#69]
Can someone please confirm if these Repos are still working as I am unable to download anything.  I keep getting time out or closed the connection?  I appreciate your help

**Comment by paliarush** [comment]
Yes, it should work. There are nightly builds running on Travis https://travis-ci.com/magento/magento2-kubernetes-devbox

Please make sure you have git permissions configured properly. Try 
```git clone git@github.com:magento/magento2.git``` 
in the CLI

**Comment by JackWormUK** [comment]
Hi @paliarush .  Thanks for coming back to me.  I found the issue was DNS as reported here
[https://github.com/kubernetes/minikube/issues/3860](https://github.com/kubernetes/minikube/issues/3860)
